# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

company_name: Vivada
company_name_lower-case: vivada

title: Vivada Tech Wiki
description: A documentory guide for all Essentials for Vivada Tech
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vivada.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: Vivada-io/wiki # for github-metadata

permalink: pretty

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  # theme test code
  - fixtures/

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: "k"

# For copy button on code
enable_copy_code_button: true

# By default, consuming the theme as a gem leaves mermaid disabled; it is opt-in
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"
  # Put any additional configuration, such as setting the theme, in _includes/mermaid_config.js
  # See also docs/ui-components/code
  # To load mermaid from a local library, also use the `path` key to specify the location of the library; e.g.
  # for (v10+):
  # path: "/assets/js/mermaid.esm.min.mjs"
  # for (<v10):
  # path: "/assets/js/mermaid.min.js"
  # Note: copy both `mermaid.esm.min.mjs` (v10+) or `mermaid.min.js` (<v10) and the associated `.map` file from the specified version of `mermaid/dist` to `/assets/js/`.

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Vivada Tech Wiki on GitHub":
    - "https://github.com/Vivada-io/wiki"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# External Websites and resources links. These sites open in new tab by following the logic provided in "_includes\js\custom.js"
external_source:
  vivada_tech: "https://vivada.tech"
  the_startup_club: "https://thestartupclub.info/"
  the_debate_club: "https://thedebateclub.info"
  shuddhi: "https://shuddhi.io"
  shuddhi_trust: "https://shuddhitrust.org/"
  discord: "https://discord.com/download"
  stream: "https://getstream.io"
  microsoft_outlook: "https://www.microsoft.com/en-us/microsoft-365/outlook/email-and-calendar-software-microsoft-outlook"
  mail_client_setup_vid_01: "https://drive.google.com/file/d/14IJWBL-xRaWNx2kUbdtgTaghBzOLm1VF/view?usp=sharing"
  mail_client_setup_vid_02: https://docs.google.com/document/d/1Htdl9dp5pCURAxfmyCreqcBV7EXnox3Y-oMw31gHi-s/edit?usp=sharing
  vivada_tech_vpn: "https://vpn.vivada.tech"
  miro_user_action_flow: "https://miro.com/app/board/uXjVNa1YGTE=/?share_link_id=939315033805"
  vs_code_download: "https://code.visualstudio.com/download"
  vivada_google_ux_sheet: "https://docs.google.com/spreadsheets/d/1f173nz8HOJZefSP_QddFzn3ZbRqZsFgIYHUvsUICz9U/edit#gid=1733308482"
  gitignore: "https://github.com/github/gitignore"
  vs_code_extension:
    git_lens: "https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens"
    prettier: "https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode"
    angular_language_service: "https://marketplace.visualstudio.com/items?itemName=Angular.ng-template"
    docker: "https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker"
    python: "https://marketplace.visualstudio.com/items?itemName=ms-python.python"
    django: "https://marketplace.visualstudio.com/items?itemName=batisteo.vscode-django"
  node_version_manager_github: "https://github.com/nvm-sh/nvm?tab=readme-ov-file#installing-and-updating"
  kt_videos:
    ui_code_walkthrough: "https://youtu.be/DhU-J_sPrSw"
    api_code_walkthrough: "https://youtu.be/Kp_UR-4bSAE"
    in_app_notifcations: "https://youtu.be/1Vo2buDZkjU"
    devops: "https://youtu.be/lHpL4L0TZCs"
    chatgpt_api_integration: "https://youtu.be/gTr2FYXtEgU"
  django: "https://www.djangoproject.com/"
  postgresql: "https://www.postgresql.org/"
  docker: "https://www.docker.com"
  redis: "https://www.redis.io"
  graphql: "https://graphql.org/"
  web_programming_by_edx: "https://www.edx.org/learn/web-development/harvard-university-cs50-s-web-programming-with-python-and-javascript"
  react_native_by_class_central: "https://www.codecademy.com/learn/learn-react-native"
  git_course_by_ibm: "https://www.edx.org/learn/github/ibm-git-and-github-basics"
  expo_additional_source:
    debugging_react_native: "https://youtu.be/BayDYRigP5I?si=bzmhU4guQdUIyBo2"
    youtube_video_01: "https://youtu.be/y6DwGxe2E_k?si=AyqWLArOFD7aN-3S"
    youtube_video_02: "https://youtu.be/iDZBeIgcixk?si=A7KlrIUEdIezNJ2v"
    youtube_video_03: "https://youtu.be/cs-zgHjt5RQ?si=Bh9ZlI-YP7nWxGuI"
    youtube_video_04:
      part_01: "https://www.youtube.com/live/a_EdG30oGQI"
      part_02: "https://www.youtube.com/live/tUjv8LppDc4?si=q5wVs1b86E5YLnIJ"
    youtube_video_05: "https://youtu.be/GYVZ4X2MtiI?si=ry3tt5Dvx41CPOss"
    youtube_video_06: "https://www.locofy.ai/convert/figma-to-react-native"
  backend_addition_source:
    api_using_django_and_graphql: "https://youtube.com/playlist?list=PLOLrQ9Pn6caxz00JcLeOR-Rtq0Yi01oBH&si=kiflVaBdq35K6ttY"
    docker_compose_with_django: " https://www.youtube.com/watch?v=mScd-Pc_pX0"
    intro_to_docker_compose: "https://youtu.be/vQmk9moF8vw?si=alqurvwJ0FyuJIZf"
    docker_for_absolute_beginners: "https://www.youtube.com/watch?v=pg19Z8LL06w"
    dockerfile_vs_docker_compose: "https://youtu.be/Z44UJUXsOGA?si=4_2A3g3ZUNtXWrbs"
    docker_for_dummies: "https://youtu.be/pTFZFxd4hOI?si=O_RD3NzTj2me43VY"
    # intro_to_django_graphql: "https://youtu.be/kP7wQoFXUSc?si=AUwrs_MVWUTfbQbi"
    # graphql_queries: "https://youtu.be/unz3RgL9A-Y?si=TvXHUiCDlqqq7O-P"
    # graphql_crud: "https://youtu.be/3819x3b43Ok?si=WL7C65Teo-P2FifK"
    django_nginx: "https://youtu.be/N2t7L_K5LXo?si=MlQyCpC3gghLhbzu"
    novu_api_overview: "https://docs.novu.co/api-reference/overview"

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# External navigation links
nav_external_links:
  # - title: Vivada Tech Wiki on GitHub
  #   url: https://github.com/Vivada-io/wiki

liquid:
  error_mode: strict
  strict_filters: true

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a> <a href=\"https://www.netlify.com/\">This site is powered by Netlify.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/Vivada-io/wiki" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
# Note: the main Just the Docs site does *not* use Google Analytics.
# ga_tracking: UA-2709176-10,G-5FG1HLH3XQ
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all

# Terms that developer should be familiar with
terms:
  - Git
  - Git pull, push, merge, commit, stage, stash
  - Create merge request (create pull request)
  - Docker
  - Docker Compose
  - Docker services
  - Redis
  - Caching (client-side vs server-side)
  - GraphQL
  - Package.json
  - npm script
  - Netlify
  - Capacitor package
  - D3.js
  - Environment variables
  - Nginx
  - Novu
  - Celery
  - Jenkins
  - CI/CD pipelines
  - Postgres
  - Kubernetes
  - Grafana
  - Sonar Qube
  - AWS
